language: rust

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install gcc g++ make libsdl1.2-dev

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo '<meta http-equiv=refresh content="0;url=rslike/index.html">' > target/doc/index.html &&
  git config --global user.email "travis@travis-ci.org" &&
  git config --global user.name "travis-ci" &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

env:
  global:
    secure: tIpj3IG54S6H647yX58npmeGQy1/SC5/oiyZVcGdbUxNqd3Wja2EptkcgYAIMdfqFniMhuo8GDUavFnw4pCJH/l2/aIUb27igVS6ZLd+htVk3cch0Mc8qw2lq2mjHkL53y7rD2cILkoQuX8HvE6b6rz1g/A/gmmlJ9S1yLWfuRE=
